### ISSUE TITLE
council source website changed

### ISSUE THREAD

**Issue by seb-1204** [planningalerts-scrapers/pittwater#3]
The original address for scraping http://portal.pittwater.nsw.gov.au/internet/modules/TrackingDA is no longer working (approximately since December 2017 judging by [the graph](https://www.planningalerts.org.au/authorities/pittwater))

The new site (if I'm not mistaken) is https://www.planningportal.nsw.gov.au/alerts and gives provision for some form of alert.

**Comment by seb-1204** [comment]
there is also some OpenData page on the site: https://www.planningportal.nsw.gov.au/opendata/

**Comment by LoveMyData** [comment]
Pittwater council has been merged with Northern Beaches council on 12 May 2016. Please let us know if any specific DA that is missing from Northern Beaches council and we will investigate the reason(s) behind it.

Will mark this issue as 'won't fix'
